### ISSUE TITLE
可以增加推送爬虫(push_open.js)嘛？

### ISSUE THREAD

**Issue by mlabalabala** [jadehh/TV#3]
![image](https://github.com/jadehh/TV/assets/91363385/23e913f1-0885-475d-be78-6131af86491e)

**Comment by mlabalabala** [comment]
https://raw.githubusercontent.com/catvod/CatVodOpen/main/nodejs/src/spider/video/push.js
### 源推送

**Comment by jadehh** [comment]
> https://raw.githubusercontent.com/catvod/CatVodOpen/main/nodejs/src/spider/video/push.js
> 
> ### 源推送

源推送我没用过，具体描述下功能呢，是不是扫码推送。

**Comment by mlabalabala** [comment]
### catvod的配置文件中增加
```
{
    "key": "push_agent",
    "name": " | 推送 | ",
    "type": 3,
    "api": "push.js",
    "ext": ""
}
```
### key为push_agent时catvod识别为推送
![image](https://github.com/jadehh/TV/assets/91363385/7d6c1969-942b-46e7-836c-cfca19323a28)
### 点击推送按钮之后，识别剪贴板内容

### 爬虫代码里实现检查剪贴板内容是否支持播放的方法，```__jsEvalReturn()```返回对象中中增加support键值
```
async function check(args) {
    /**
     * @params 字符串 -> 剪贴板|内容
     * @return 布尔 -> 该是否支持通过CatVod播放
    */
    return true;
}
...
export function __jsEvalReturn() {
    return {
        support: check,
        init: init,
        detail: detail,
        play: play,
    };
}
```



## 大概实现代码
```
class PushAgent extends Spider {
    constructor() {
        super();
    }

    async init(cfg) {
        // cfg["skey"] 必须为push_agent 才能再界面上显示点击按钮
        await super.init(cfg);
    }

    async setDetail(pushStr) {
        /**
         * @params pushStr 字符串 -> 剪贴板内容
        */
        
        // TODO 处理pushStr

        
    }

}

let spider = new PushAgent()

async function check(args) {
    /**
     * @params 字符串 -> 剪贴板|内容
     * @return 布尔 -> 该是否支持通过CatVod播放
    */
    return true;
}

async function init(cfg) {
    await spider.init(cfg)
}

async function detail(id) {
    return await spider.detail(id)
}

async function play(flag, id, flags) {
    return await spider.play(flag, id, flags)
}

export function __jsEvalReturn() {
    return {
        support: check,
        init: init,
        detail: detail,
        play: play,
    };
}
```

**Comment by jadehh** [comment]
##  推送格式
关于推送格式的内容具体有什么模版吗，比如像影视是直接推送播放连接，还是有自定义的需求。

**Comment by jadehh** [comment]
完成本地推送的功能，可以看下https://github.com/jadehh/TV/blob/js/js/push_agent.js

**Comment by mlabalabala** [comment]
> ## 推送格式
> 关于推送格式的内容具体有什么模版吗，比如像影视是直接推送播放连接，还是有自定义的需求。

推送格式的话除了播放连接（像.m3u8  .mp）通过目前的处理应该可以播放，还有一种像阿里云盘的分享链接或者夸克盘的分享链接可能还需要再处理才行

**Comment by jadehh** [comment]
好的目前只有直链能播放，阿里的那套后续会考虑加上，夸克的暂不支持

**Comment by jadehh** [comment]
> > ## 推送格式
> > 关于推送格式的内容具体有什么模版吗，比如像影视是直接推送播放连接，还是有自定义的需求。
> 
> 推送格式的话除了播放连接（像.m3u8 .mp4）通过目前的处理应该可以播放，还有一种像阿里云盘的分享链接或者夸克盘的分享链接可能还需要再处理才行，应该把玩偶哥哥处理detail那套搬过来就行

好的目前只有直链能播放，阿里的那套后续会考虑加上，夸克的暂不支持

**Comment by mlabalabala** [comment]
👍

**Comment by mlabalabala** [comment]
🤙

**Comment by mlabalabala** [comment]
👍
